### ISSUE TITLE
Add Darwin arm64 support

### ISSUE THREAD

**Issue by aaaaahaaaaa** [snowplow-devops/terraform-provider-redash#12]
Any chance you could provide a arm64  build to support Apple silicon?

**Comment by jbeemster** [comment]
Hey @aaaaahaaaaa I can't test this personally as I do not have an M1 macbook but in the releases page you should see a `linux_arm64` build: https://github.com/snowplow-devops/terraform-provider-redash/releases/tag/v0.5.0

Is that binary not working for you?

**Comment by aaaaahaaaaa** [comment]
When initiating the providers, Terraform is looking for a `darwin_arm64` build on the M1.

**Comment by jbeemster** [comment]
Ahh sorry yes of course - ill see if our releaser package can build for that one as well.

**Comment by aaaaahaaaaa** [comment]
Great, thanks!

**Comment by jbeemster** [comment]
Seems the only change needed is bumping Go to >= 1.16 - will put a PR together shortly.

**Comment by jbeemster** [comment]
@aaaaahaaaaa can you give it a try now with v0.6.0?

**Comment by aaaaahaaaaa** [comment]
Working! Thanks for the blazing fast support ;)

**Comment by jbeemster** [comment]
No worries!  Happy to help.
